MedicDiary/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as authentication_views


urlpatterns = [

    path('admin/', admin.site.urls),
    path('', include('centralapp.urls')),
    path('', include('doctor.urls')),
    path('', include('patient.urls')),
    path('login/',authentication_views.LoginView.as_view(template_name='MedicDiary/login.html'),name='login'),
]

from django.conf import settings
from django.conf.urls.static import static

urlpatterns += [
    # ... the rest of your URLconf goes here ...
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

centralapp/urls.py
from . import views
from django.urls import path
from django.contrib.auth import views as authentication_views

app_name = 'centralapp'
urlpatterns = [

    path('',views.mainpage,name='mainpage'),
    path('About_us/',views.About_us,name ='About_us'),
    path('Aids/',views.Aids,name ='Aids'),
    path('Cancer/',views.Cancer,name ='Cancer'),
    path('Covid-19/',views.Covid_19,name ='Covid_19'),
    path('Diabetes/',views.Diabetes,name ='Diabetes'),
    path('FAQS/',views.FAQS,name ='FAQS'),
    path('Heart_disorder/',views.Heart_disorder,name ='Heart_disorder'),
    path('medical_practitioners/How_to_use',views.doc_how_to_use,name ='doc_how_to_use'),
    path('friends-and-family/How_to_use',views.patients_how_to_use,name ='patients_how_to_use'),
    path('Hypertension/',views.Hypertension,name ='Hypertension'),
    path('Inside_health_records/',views.Inside_health_records,name ='Inside_health_records'),
    path('login/',views.login,name='login'),
    path('logout/',views.logout_user,name='logout'),
    # path('logout/', authentication_views.LogoutView.as_view(template_name='centralapp/logout.html'), name='logout'),
     path('searchBar/',views.searchBar,name='searchBar'),
]

doctor/urls.py
from . import views
from django.urls import path
from django.contrib.auth import views as authentication_views

app_name = 'doctor'
urlpatterns = [
    path('doctorProfile/', views.doctorProfile, name='doctorProfile'),
    path('createDoctorProfile/',views.create_doctorprofile,name ='create_doctorprofile'),
    path('doctorRegister/',views.doctorRegister,name = 'doctorRegister'),
    path('PatientList/',views.PatientList,name = 'PatientList'),
    path('pat_profile/<int:p>', views.pat_profile,name = 'pat_profile'),
    path('newReport/<int:p>',views.newReport,name="newReport"),
    path('addReport/',views.addReport,name="addReport"),
    path('addPatient/',views.addPatient,name="addPatient"),
    path('editdocprofile/',views.editdoctorprofile,name="editdoctorprofile"),

    # path('logout/', authentication_views.LogoutView.as_view(template_name='centralapp/logout.html'), name='logout'),
    # path('mypatients',views.mypatients,name = "mypatients"),
    # path('editDoctor/',views.editDoctor,name = 'editDoctor'),
]















# =============================================================================================
# =============================================================================================


    #   path('registerpage/',views.registerpage,name ='registerpage'),
    #    path('signup/',views.signup, name ='signup'),
    #      path('logind/',views.loginn, name ='logind'),
    #       path('myPatients/', views.myPatients, name='myPatients'),
    #   #     path('doctorProfile/', views.doctorProfile, name='doctorProfile'),
    #       path('addpatient/', views.addpatient, name='addpatient'),
    #       path('doctorRecords/<str:p_username>', views.doctorRecords, name='doctorRecords'),
    #        path('addRecord/', views.addRecord, name='addRecord'),
    #         path('newReport/', views.newReport, name='newReport'),
    #
    #
    # path('doctorprofile/', views.doctor_profile, name='doctor_profile'),
    #
    #
    #
    # # path('doclogin/',views.doclogin,name ='doclogin'),
    # # path('docregister/',views.docregister,name ='docregister')

doctor/forms.py
from django import forms
from django.contrib.auth.models import User                    #its a model that defines the parameters of a user
from django.contrib.auth.forms import UserCreationForm
from .models import DoctorProfile

class DoctorRegisterForm(UserCreationForm):                         # the form created by us is in a form of a class
    email = forms.EmailField()
    password1 = forms.CharField(help_text='Your password can’t be too similar to your other personal information. <br>Your password must contain at least 8 characters.<br>Your password can’t be a commonly used password.<br>Your password can’t be entirely numeric.')

    class Meta:                                               # a meta class defines/builds upon the current class..
        model = User
        fields = ['username','email','password1','password2']

class DoctorProfileForm(forms.ModelForm):
    class Meta:
        model = DoctorProfile
        fields = ('name','phone','Specialisation','City','Registration_Number','Registration_Council','Registration_year','Degree','College','Year_of_completion','Medical_registration_proof','Current_place_of_work','Gender','Profile_pic','Aadhar_Number')

doctor/views.py
from django.shortcuts import render,redirect, get_object_or_404
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate,login,logout
from django.contrib import messages
from .forms import DoctorRegisterForm, DoctorProfileForm
from django.contrib.auth.decorators import login_required
from .models import DoctorProfile
# from django.views import View
from .models import DoctorProfile,PatientDocConfig
from patient.models import PatientProfile,PatientVitals,LabReports,Records
import datetime
def doctorRegister(request):
    if request.method =='POST':
        form = DoctorRegisterForm(request.POST)
        if form.is_valid():
            # form.save()
            # username = form.cleaned_data.get('username')
            # email = form.cleaned_data.get('email')
            # return redirect('login')
            user = form.save(commit=False)
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            usertype = 2
            user.set_password(password)
            user.save()
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('doctor:create_doctorprofile')
    else:
        form = DoctorRegisterForm()
    return render(request,'doctor/doctorRegister.html',{'form':form})

@login_required
def create_doctorprofile(request):
    if request.method =='POST':
        form = DoctorProfileForm(request.POST)
        
        if form.is_valid():
            doctor = form.save(commit=False)
            doctor.doctor = request.user
            doctor.save()
            # form.doctor = request.user
            # form.save()
            return redirect('doctor:doctorProfile')
        else:
            print("here1")
            
    else:
        print("here")
        form = DoctorProfileForm()
    return render(request,'doctor/doctor-profile-create.html',{'form':form})


@login_required
def doctorProfile(request):
    profile = DoctorProfile.objects.get(doctor=request.user)

    return render(request, 'doctor/doctor_profile.html',{'profile':profile})


@login_required
def PatientList(request):
    # listed = Mypatients.objects.get(doctorp = request.user).mypatientlist
    # if len(listed) ==0:
        # return HttpResponse("emply:(")
    # patientsl = PatientProfile.objects.getall()
    pats=PatientDocConfig.objects.filter(doctor_id=request.user.id)
    print(len(pats))

    patient_l=[]
    for p in pats:
        print("hello")
        patient_l.append(PatientProfile.objects.filter(access_code=p.access_code)[0])

    Patient_list=PatientProfile.objects.filter()
    print(len(patient_l))


    return render(request, 'doctor/patientList.html',{'patientl':patient_l})


@login_required
def pat_profile(request,p):
    print(p)
    
   
   
    subject=PatientProfile.objects.filter(id=p)[0]
    pat_user=User.objects.get(id=subject.userid)
    
    pat_vitals=PatientVitals.objects.filter(patientv=pat_user)
    all_reports=Records.objects.filter(patient_id=p).order_by('id').reverse()
    
    all_lab=LabReports.objects.filter(patientl=pat_user).order_by('id').reverse()
    
    print(len(all_lab))
    print(len(pat_vitals))

    
    for report in all_reports:
        des=report.medication
        med=des.split(":")
        m_list=[]
        for m in med:
	        dosage=m.split("/")
	        m_list.append(dosage)
 
        report.medication=m_list
        
        
    return render(request,'doctor/patient_records_in_doc.html',{'subject':subject,"vitals":pat_vitals.first(),'Reports':all_reports,"labreports":all_lab})

@login_required
def newReport(request,p):
    doctor=DoctorProfile.objects.filter(doctor=request.user)[0]
    patient=PatientProfile.objects.filter(id=p)[0]
    date=str(datetime.datetime.now()).split(" ")[0]

    obj={'doctor_name':doctor.name,'patient_name':patient.name,'date':date,"docid":doctor.id,"patid":patient.id}
    return render(request,'doctor/report.html',{'details':obj})

@login_required
def addReport(request):
    if request.method=="POST":
        new_record=Records()
        new_record.date=str(datetime.datetime.now()).split(" ")[0]
        new_record.diagnosis=request.POST['diagnosis']
        new_record.doctor_name=request.POST['doctor_name']
        new_record.Symptoms=request.POST['symptoms']
        new_record.medication=request.POST['medication']
        new_record.patient_id=request.POST['patid']
        new_record.doctor_id=request.POST['docid']
        new_record.additional_precautions=request.POST['additional_precautions']
        new_record.save()
        addr='doctor:pat_profile/'+ str(request.POST['patid'])

        return redirect('/pat_profile/'+ str(request.POST['patid']))

@login_required
def addPatient(request):
    print("entered1")
    
    accesscode=request.POST['accesscode']
    print(accesscode)
    print("entered")
    if len(PatientProfile.objects.filter(access_code=accesscode))==0:
        return redirect('/PatientList/')
    else:
        print("heya")
        check_pat=PatientProfile.objects.filter(access_code=accesscode)[0]
        print(check_pat.access_code)
        
           
        new_config=PatientDocConfig()
            
        new_config.doctor_id=request.user.id
        new_config.access_code=accesscode
        new_config.save()
        return redirect('/PatientList/')
        
@login_required
def editdoctorprofile(request):
    doctor = get_object_or_404(DoctorProfile, doctor=request.user)
    # patient = PatientProfile.objects.get(patient=request.user)
    # if request.method == 'POST':
    form = DoctorProfileForm(request.POST, request.FILES, instance=doctor)
    # if request.method == 'POST':

    if form.is_valid():
        doctor = form.save(commit=False)
        doctor.doctor = request.user
        doctor.save()
        return redirect('doctor:doctorProfile')
    # else:
    #     form = PatientProfileForm()
    return render(request,'doctor/doctor_profile_edit.html',{'form':form})

# @login_required
# class mypatients(View):
#     def get(self,request):
#         return render(request, 'doctor/temp.html',{})






















# ========================================================================
# ========================================================================

#
# from .models import doc_details,patient_doc_config,records
# from django.contrib.sessions.models import Session
# from patient.models import patient_details
#
# # Create your views here.
# def doctor_profile(request):
#     return render(request,'doctor/doctor_profile.html')
#
# def doctorRecords(request):
#     return render(request, 'doctor/doctor_records.html')
#
# def registerpage(request):
#     return render(request,'doctor/register.html')
#
#
#
#
# def signup(request):
#     if request.method=="POST":
#         fname=request.POST['fname']
#         lname=request.POST['lname']
#
#         username=request.POST['username']
#         password=request.POST['password']
#         email=request.POST['email']
#
#
#
#         if len(username)>15:
#             messages.error(request,'length of username should be less than15')
#             return redirect('patient:registerpage')
#
#
#
#         myuser=User.objects.create_user(username,email,password)
#         myuser.first_name=fname
#         myuser.last_name=lname
#
#         new_doc=doc_details()
#         new_doc.lname=lname
#         new_doc.fname=fname
#         new_doc.username=username
#         new_doc.email=email
#         new_doc.save()
#
#         myuser.save()
#
#         newPatient=patient_doc_config()
#         newPatient.patient_username="sample_pusername"
#         newPatient.doctor_username=username
#         newPatient.auth_key=123
#         newPatient.save()
#
#         messages.success(request, 'Form submission successful')
#         return redirect('/')
#
#
#     else :
#         return HttpResponse('404-not found')
#
#
# def loginn(request):
#     if request.method=="POST":
#         username=request.POST['username']
#         password=request.POST['password']
#         user=authenticate(username=username,password=password)
#         if user is not None:
#             login(request,user)
#             print("innn")
#             request.session["username_d"]=username
#             return render(request,'doctor/doctor_profile.html',{"username":username})
#
#         else :
#             print("invalid credentials")
#             return render(request,'centralapp/mainpage.html')
#
#
#         return HttpResponse('login')
#
#
#
#     else:
#         return HttpResponse('404-not found')
#
# def myPatients(request):
#     username=request.session["username_d"]
#     if len(patient_doc_config.objects.filter(doctor_username=username))!=0:
#         pat=patient_doc_config.objects.filter(doctor_username=username)
#         return render(request, 'doctor/mypatients.html',{"patients":pat})
#
#     else :
#         return render(request, 'doctor/mypatients.html',{"patients":"add patients"})
#
#
#     return render(request, 'doctor/mypatients.html',{"username":username})
#
# def doctorProfile(request):
#     return render(request, 'doctor/doctor_profile.html')
#
# def addpatient(request):
#     if request.method=="POST":
#         p_username=request.POST['username']
#         accesscode=request.POST['accesscode']
#
#         if len(patient_details.objects.filter(username=p_username))!=0:
#             pat=patient_details.objects.get(username=p_username)
#             if  pat.auth_key==accesscode:
#
#                 newPatient=patient_doc_config()
#                 newPatient.patient_username=p_username
#                 newPatient.doctor_username=request.session["username_d"]
#                 newPatient.auth_key=accesscode
#                 newPatient.save()
#                 redirect('doctor:myPatients')
#             else :

doctor/templates/doctor/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>

	<!-- Required meta tags -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<!-- Bootstrap CSS -->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
		integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Pacifico" />
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Cinzel" />
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Oswald" />
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Grandstander" />
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Ubuntu" />
	<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Itim" >

	<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
	<script src="https://kit.fontawesome.com/032a738741.js" crossorigin="anonymous"></script>

	<link rel="stylesheet" href="{% static 'doctor/css_files/style.css' %}">
	<link rel="icon" type="image/png" href="{% static 'doctor/Images/icon.png' %}" />
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
	<link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
	<script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
	<script src="{% static 'doctor/js/app.js' %}"></script>
	<!--<script src="https://kit.fontawesome.com/b99e675b6e.js"></script>-->
	<title>PHD Project</title>
</head>

<body style="background: #f7f7ee">
	<script>
		AOS.init();
		document.getElementById("defaultOpen").click();
	</script>
	<nav class="navbar navbar-expand-lg navbar-light nav-bg" id="navstyle">
		<a class="navbar-brand" href="{% url 'centralapp:mainpage' %}"
			style="font-family: Cinzel; font-size: 40px !important; color: white;">
			<img src="{% static 'doctor/Images/icon.png' %}" width="50" height="50" class="d-inline-block align-top"
				alt="" loading="lazy">
				PHD Project
		</a>

		<div class="collapse navbar-collapse" id="navbarSupportedContent" style="font-size:20px; ">
			<ul class="navbar-nav ml-auto">
				<!-- <li class="nav-item active">
					<a class="nav-link" href="#" style="color: rgb(0, 0, 0)"> Sign In </a>
				</li> -->
				<!-- <li class="nav-item active">
					<a class="nav-link" href="{% url 'centralapp:logout' %}" style="color: rgb(0, 0, 0)"> Logout </a>
				</li> -->
				{% if user.is_authenticated %}
				<li class="nav-item dropdown">
					<a class="nav-link " style="background:#3a8684;color:white;border-radius: 8px;" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" >
						Hey {{request.user.username|title }}
					</a>
					<div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
						<a class="dropdown-item nav-link" href="" style="color: rgb(0, 0, 0)"> My Profile </a>
						<a class="dropdown-item nav-link" href="{% url 'centralapp:logout' %}" style="color: rgb(0, 0, 0)"> Logout </a>
					</div>
				</li>
				{% endif %}
			</ul>
		</div>
	</nav>

	{% with 'create_doctorprofile doctorRegister' as list%}
		{% if request.resolver_match.url_name not in list.split %}

		<div id="sidebar">
			<div class="toggle-btn" onclick="toggleSideBar()">
				<span style='font-size:20px;'>&#9776;</span>
			</div>

			<ul>
				<a class="tablinks" href="{% url 'doctor:PatientList' %}">
					<li>My Patients</li>
				</a>
				<a class="tablinks" href="{% url 'doctor:doctorProfile' %}">
					<li>My Profile</li>
				</a>
			</ul>
		</div>
		{%endif%}
		{% endwith%}

	<!-- <div id="main-content">
		<div class="tabcontent" id="myPatients">
			Hey this is my patients page holla,aa,l,c
		</div>
		<div class="tabcontent" id="myProfile">
			Hey this is my profile page
		</div>
	</div>
	 -->
	{% block doctorbase %}
	{% endblock %}

	<!-- Footer -->
	<footer class="page-footer footer font-small mdb-color" style="background:linear-gradient(90deg, #24a19c,#cedebd);">
		<div class="row text-center ml-5 text-md-left">
			<hr class="w-100 clearfix d-md-none">
			<div class="col-md-3 col-lg-3 col-xl-3 mx-auto mt-3 footer-style">
				<h6 class="text-uppercase mb-2 ">Know-hows</h6>
				<p>
					<a href="{% url 'centralapp:Inside_health_records' %}" class="useful_links">What's in my health
						record</a><br>
					<a href="{% url 'centralapp:patients_how_to_use' %}" class="useful_links">How to use my health
						record</a><br>
					<a href="{% url 'centralapp:doc_how_to_use' %}" class="useful_links">How to use the health record
						(for doctors)</a><br>
					<a href="{% url 'centralapp:FAQS' %}" class="useful_links">FAQs</a><br>
				</p>
			</div>
			<div class="col-md-3 col-lg-3 col-xl-3 mx-auto mt-3 footer-style">
				<h6 class="text-uppercase mb-2 font-weight-bold"> Other useful links</h6>
				<div class="no-bullet-list two-column-list">
					<!-- <a href="{% url 'centralapp:Covid_19' %}" class="useful_links">Covid-19 checkpoints</a> -->
<br>
					<h6 class="mt-2 font-weight-bold">Learn about diseases</h6>
					<ul>
						<li><a href="{% url 'centralapp:Cancer' %}" class="useful_links">Cancer</a><br></li>
						<li><a href="{% url 'centralapp:Aids' %}" class="useful_links">AIDS</a><br></li>
						<li><a href="{% url 'centralapp:Diabetes' %}" class="useful_links">Diabetes</a><br></li>
						<li><a href="{% url 'centralapp:Heart_disorder' %}" class="useful_links">Heart Disorders</a><br>
						</li>
						<li><a href="{% url 'centralapp:Hypertension' %}" class="useful_links">Hypertension</a><br></li>
					</ul>
				</div>
			</div>
			<hr class="w-100 clearfix d-md-none">
			<div class="col-md-2 col-lg-2 col-xl-2 mx-auto mt-3 no-bullet-list footer-style">
				<h6 class="text-uppercase mb-2 font-weight-bold">Our Team</h6>
				<ul>
					<li>Vinita Patil<br></li>
				</ul>
				<a href="{% url 'centralapp:About_us' %}" class="useful_links" style="font-weight:bold">More about
					us</a>
			</div>
			<hr class="w-100 clearfix d-md-none ">
			<div class="col-md-3 col-lg-3 col-xl-3 mr-5 mt-3 footer-style">
				<h6 class="text-uppercase mb-2 font-weight-bold ">Contact</h6>
				<p>
					<i class="fa fa-home mr-3"></i>Jalgaon
				</p>
				<p>
					<i class="fa fa-envelope mr-3 "></i> vinita.patil
				</p>
				<p>
					<i class="fa fa-phone mr-3"></i> +91 0000000000
				</p>

			</div>
		</div>
		<hr>
		<div class="row d-flex align-items-center footer-style">
			<!-- Grid column -->
			<div class="col-md-11 col-lg-11">
				<!--Copyright-->
				<p class="text-center">© 2024 Copyright:
					<strong> PHD Project</strong>
				</p>
			</div>
		</div>
	</footer>

</body>

</html>

doctor/templates/doctor/doctor_base.html
{% extends 'doctor/base.html' %}

{% block body %}
{% load static %}
<div id="sidebar">
    <div class="toggle-btn" onclick="toggleSideBar()">
        <span style='font-size:20px;'>&#9776;</span>
    </div>
    <a href="#" class="btn-close" onclick="closeSideBar()">&times;</a>

    <ul>
        <li><a href="{% url 'doctor:PatientList' %}">My Patients</a></li>
        <li><a href="{% url 'doctor:doctorProfile' %}">My Profile</a></li>
        <li><a href="#">Back to homepage</a></li>

    </ul>

</div>

{% block doctor_base %}
{% endblock %}


{% endblock %} 

doctor/templates/doctor/patientList.html
{% extends 'doctor/base.html' %}
{% block doctorbase %}
<div class="tabcontent" id="myPatients" >
<div id="main-content">
<div class="container">
    <p style="text-align: center;font-family:'Ubuntu';font-size: 3rem;text-align: center; color: rgb(92, 46, 13); ">Patient's List</p>
</div>
<div class="container" style="margin: auto;">
    <table class="table">
        <thead class="thead-dark">
            <tr>
                <th scope="col">Patient Name</th>
                <th scope="col">Contact Number</th>
                <th scope="col">Patient Profile</th>
            </tr>
        </thead>
        <tbody>
            {% for item in patientl %}
            <tr>
                <td>{{item.name}}</td>
                <td>{{item.phone}}</td>
                <td><button class="edit-option-buttons"><a href="{% url 'doctor:pat_profile' p=item.id %}">Patient Profile</a></button></td>
            </tr> 
            {% empty %}
            <tr><td colspan="3" style="font-size: 20px;"><b> No Patients Added.</b></td></tr>
            {%endfor%}
            <tr>
                <td colspan="3">
                    <span style="float:right">
                        <button class="edit-option-buttons">
                            <a href="#" data-toggle="modal" data-target="#accessmodal"> Add a new patient </a>
                        </button>
                    </span>
                </td>
            </tr>
        </tbody>
    </table>
    <div>
        {% for message in messages %}
        <h3>{{message}}</h3>
        {% endfor %}
    </div>
</div>


<div class="modal fade" id="accessmodal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-notify modal-warning" role="document">
        <!--Content-->
        <div class="modal-content">
            <!--Header-->
            <div id="signincard" class="card">
                <div id="cardhead" class="card-header bg-warning mb-2">
                    <div class="card-title text-center h4" >Add a Patient</div>
                </div>

                <!-- Input Fields -->
                <form action="{% url 'doctor:addPatient' %}" method="POST">
                    {% csrf_token %}
                   
                 <input type="text" id="accessCode" class="form-control mb-2" placeholder="Enter the access code"
                        name="accesscode">
                    <!-- Login Button -->
                    <div class="text-center">
                        <button class="btn my-2" id="login" type="submit">Submit</button>
                    </div>
                </form>
               
            </div>
            
        </div>
        <!--/.Content-->
    </div>
</div>
</div>
</div>


{% endblock %}