MedicDiary/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as authentication_views


urlpatterns = [

    path('admin/', admin.site.urls),
    path('', include('centralapp.urls')),
    path('', include('doctor.urls')),
    path('', include('patient.urls')),
    path('login/',authentication_views.LoginView.as_view(template_name='MedicDiary/login.html'),name='login'),
]

from django.conf import settings
from django.conf.urls.static import static

urlpatterns += [
    # ... the rest of your URLconf goes here ...
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

centralapp/urls.py
from . import views
from django.urls import path
from django.contrib.auth import views as authentication_views

app_name = 'centralapp'
urlpatterns = [

    path('',views.mainpage,name='mainpage'),
    path('About_us/',views.About_us,name ='About_us'),
    path('Aids/',views.Aids,name ='Aids'),
    path('Cancer/',views.Cancer,name ='Cancer'),
    path('Covid-19/',views.Covid_19,name ='Covid_19'),
    path('Diabetes/',views.Diabetes,name ='Diabetes'),
    path('FAQS/',views.FAQS,name ='FAQS'),
    path('Heart_disorder/',views.Heart_disorder,name ='Heart_disorder'),
    path('medical_practitioners/How_to_use',views.doc_how_to_use,name ='doc_how_to_use'),
    path('friends-and-family/How_to_use',views.patients_how_to_use,name ='patients_how_to_use'),
    path('Hypertension/',views.Hypertension,name ='Hypertension'),
    path('Inside_health_records/',views.Inside_health_records,name ='Inside_health_records'),
    path('login/',views.login,name='login'),
    path('logout/',views.logout_user,name='logout'),
    # path('logout/', authentication_views.LogoutView.as_view(template_name='centralapp/logout.html'), name='logout'),
     path('searchBar/',views.searchBar,name='searchBar'),
]

doctor/urls.py
from . import views
from django.urls import path
from django.contrib.auth import views as authentication_views

app_name = 'doctor'
urlpatterns = [
    path('doctorProfile/', views.doctorProfile, name='doctorProfile'),
    path('createDoctorProfile/',views.create_doctorprofile,name ='create_doctorprofile'),
    path('doctorRegister/',views.doctorRegister,name = 'doctorRegister'),
    path('PatientList/',views.PatientList,name = 'PatientList'),
    path('pat_profile/<int:p>', views.pat_profile,name = 'pat_profile'),
    path('newReport/<int:p>',views.newReport,name="newReport"),
    path('addReport/',views.addReport,name="addReport"),
    path('addPatient/',views.addPatient,name="addPatient"),
    path('editdocprofile/',views.editdoctorprofile,name="editdoctorprofile"),

    # path('logout/', authentication_views.LogoutView.as_view(template_name='centralapp/logout.html'), name='logout'),
    # path('mypatients',views.mypatients,name = "mypatients"),
    # path('editDoctor/',views.editDoctor,name = 'editDoctor'),
]















# =============================================================================================
# =============================================================================================


    #   path('registerpage/',views.registerpage,name ='registerpage'),
    #    path('signup/',views.signup, name ='signup'),
    #      path('logind/',views.loginn, name ='logind'),
    #       path('myPatients/', views.myPatients, name='myPatients'),
    #   #     path('doctorProfile/', views.doctorProfile, name='doctorProfile'),
    #       path('addpatient/', views.addpatient, name='addpatient'),
    #       path('doctorRecords/<str:p_username>', views.doctorRecords, name='doctorRecords'),
    #        path('addRecord/', views.addRecord, name='addRecord'),
    #         path('newReport/', views.newReport, name='newReport'),
    #
    #
    # path('doctorprofile/', views.doctor_profile, name='doctor_profile'),
    #
    #
    #
    # # path('doclogin/',views.doclogin,name ='doclogin'),
    # # path('docregister/',views.docregister,name ='docregister')

patient/urls.py
from . import views
from django.urls import path
from django.contrib.auth import views as authentication_views

app_name = 'patient'
urlpatterns = [
    path('Medications/', views.medications, name='medications'),
    path('LabReports/', views.labreports, name='labreports'),
    path('patientProfile/', views.patientProfile, name='patientProfile'),
    path('patientRecords/', views.patientRecords, name='patientRecords'),
    path('createPatientProfile/',views.create_patientprofile,name ='create_patientprofile'),
    path('patientvitals/',views.patientvitals_input,name ='patientvitals_input'),
    path('patientRegister/',views.patientRegister,name = 'patientRegister'),
    path('editPatient/',views.editPatient,name = 'editPatient'),
    path('editPatientVitals/',views.editPatientVitals,name = 'editPatientVitals'),
    path('addLabReports/',views.addLabReports,name = 'addLabReports'),
    path('logout/', authentication_views.LogoutView.as_view(template_name='centralapp/logout.html'), name='logout'),   
    # path('patLogin/', auth_views.login, {'template_name': 'patient/login.html'}, name = 'login'),
    # path('login/',authentication_views.LoginView.as_view(template_name='patient/patlogin.html'),name='patLogin'),
    # path('patLogout/',authentication_views.LogoutView.as_view(template_name='patient/patlogout.html'),name='patLogout'),
]














# ======================================================================================
# ======================================================================================


    # path('personalNotes/', views.personalNotes, name='personalNotes'),
    #
    #
    # # path('login/',views.login,name ='login'),
    # path('registerpage/',views.registerpage,name ='registerpage'),
    # # path('profile/',views.profile,name ='profile'),
    # # path('patientregister/',views.patientregister,name = 'patientregister'),
    # # path('makeprofilepage/',views.makeprofilepage,name = 'makeprofilepage'),
    # path('signup/',views.signup, name ='signup'),
    # path('loginp/',views.loginn, name ='loginp'),
    # path('logout/',views.logout, name ='logout'),
    #  path('addnotes/',views.addnotes, name ='addnotes'),

centralapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


class Diseases(models.Model):
    name=models.CharField(max_length=1000,blank=False)
    about=models.CharField(max_length=1000,blank=False)
    symptoms=models.CharField(max_length=1000,blank=False)
    treatment=models.CharField(max_length=1000,blank=False)

    def __str__(self):
        return self.name

centralapp/forms.py
from django import forms
from django.contrib.auth.models import User

centralapp/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from django.contrib.auth.models import auth
from django.contrib.auth import authenticate,login,logout
from django.contrib import messages
from patient.models import PatientProfile
from doctor.models import DoctorProfile
import pandas as pd
from .models import Diseases
from django.contrib import messages


# from patient.models import PatientProfile
# import requests
# from bs4 import BeautifulSoup



def mainpage(request):
    # page = request.get('')
    # soup = BeautifulSoup(page.text,'html.parser')
    # https://www.niams.nih.gov/health-topics/all-diseases
    # https://www.cdc.gov/diseasesconditions/index.html
    # https://www.pinehurstmedical.com/internalmedicine/internal-medicine-diseases-disorders-a-syndromes/
    # https://familydoctor.org/diseases-and-conditions/
    return render(request,'centralapp/mainpage.html')


def login(request):
    if request.method=='POST':
        username=request.POST['username']
        password=request.POST['password']
        user=auth.authenticate(username=username,password=password)
        if user is not None:
            auth.login(request, user)
            usert =3
            # if request.user.patient.usertype=="1":
            if PatientProfile.objects.filter(patient = request.user):
                isuser = PatientProfile.objects.filter(patient = request.user)
                usert = [int(each.usertype) for each in isuser][0]
            elif DoctorProfile.objects.filter(doctor=request.user):
                isuser = DoctorProfile.objects.filter(doctor=request.user)
                usert = [int(each.usertype) for each in isuser][0]
            # usertype = [int(each.usertype) for each in isuser][0]
            # usertype = [int(each.usertype) for each in isuser]
            if usert==1:
                # return render(request,'centralapp/temp.html',{'isuser':isuser,'usert':usert})
                return redirect('patient:patientProfile')
            elif usert==2:
                return redirect('doctor:doctorProfile')
            # return render(request,'centralapp/temp.html', {'isuser':isuser,'usertype':usertype})
        # elif request.user.doctor.usertype=="2":
        else:
            messages.info(request,"Invalid Credentials!")
            return redirect('login')
    return render(request,'centralapp/login.html')

# uniquetogether



def About_us(request):
    return render(request,'centralapp/about_us.html')
def Cancer(request):
    return render(request,'centralapp/cancer.html')
def Covid_19(request):
    return render(request,'centralapp/Covid_19.html')
def Diabetes(request):
    return render(request,'centralapp/diabetes.html')
def FAQS(request):
    return render(request,'centralapp/faqs.html')
def Heart_disorder(request):
    return render(request,'centralapp/heart_disorder.html')
def doc_how_to_use(request):
    return render(request,'centralapp/how_to_use_Doctor.html')
def patients_how_to_use(request):
    return render(request,'centralapp/how_to_use_User.html')
def Hypertension(request):
    return render(request,'centralapp/hypertension.html')
def Inside_health_records(request):
    return render(request,'centralapp/inside_health_records.html')
def Aids(request):
    return render(request,'centralapp/aids.html')


def searchBar(request):
    query=request.POST['searchBar']

    try:
        dis=Diseases.objects.get(name__icontains=query)
        return render(request,'centralapp/search_result.html',{"disease":dis})

    except :
        messages.error(request, f"Sorry! '{query}' does not exist in our Health Conditions dataset")
        return redirect('/')
    
def logout_user(request):
    logout(request)
    return redirect("/")

centralapp/templates/centralapp/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>

	<!-- Required meta tags -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<!-- Bootstrap CSS -->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
	<link rel="stylesheet"
	href="https://fonts.googleapis.com/css?family=Pacifico" />
	<link rel="stylesheet"
	href="https://fonts.googleapis.com/css?family=Cinzel" />
	<link rel="stylesheet"
	href="https://fonts.googleapis.com/css?family=Oswald"/>
	<link rel="stylesheet"
	href="https://fonts.googleapis.com/css?family=Grandstander"/>
	<link rel="stylesheet"
	href="https://fonts.googleapis.com/css?family=Ubuntu"/>

	<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
	<script src="https://kit.fontawesome.com/032a738741.js" crossorigin="anonymous"></script>

	<link rel="stylesheet" href="{% static 'centralapp/css_files/style.css' %}">
	<link rel="stylesheet" href="{% static 'centralapp/css_files/static_style.css' %}">
	<link rel="icon" type="image/png" href="{% static 'centralapp/Images/icon.png' %}"/>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"/>
	<link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
	<script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
	<script src="{% static 'centralapp/js/app.js' %}"></script>
    <!-- <script type="text/javascript" src="js/mdb.min.js"></script> -->
    <!--<script src="https://kit.fontawesome.com/b99e675b6e.js"></script>-->
	<title>PHD Project</title>
</head>
<body style="background: #f7f7ee">
	<script>
       AOS.init();
	   $(function () {
			$('[data-toggle="tooltip"]').tooltip()
		})
	</script>
	<div id="startOfPage"></div>
	<nav class="navbar navbar-expand-lg navbar-light nav-bg" id="navstyle" >
		<a class="navbar-brand" href="{% url 'centralapp:mainpage' %}" style="font-family: Cinzel; font-size: 40px !important; color: white;" >
			<img src="{% static 'centralapp/Images/icon.png' %}" width="50" height="50" class="d-inline-block align-top" alt="" loading="lazy">
			PHD Project
		</a>




		<div class="collapse navbar-collapse" id="navbarSupportedContent" style="font-size:20px; ">
			<ul class="navbar-nav ml-auto">
				<!-- <li class="nav-item active">
					<a class="nav-link" href="#" style="color: rgb(0, 0, 0)"> Sign In </a>
				</li>
				<li class="nav-item active">
					<a class="nav-link" href="#" style="color: rgb(0, 0, 0)"> Sign Up </a> -->
					{% with 'login' as list%}
					
					{% if request.resolver_match.url_name not in list.split %}
					{% if user.is_authenticated %}
					<li class="nav-item dropdown">
						<a class="nav-link" style="background:#3a8684;color:white;border-radius: 8px;" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" >
							Hey {{request.user.username }}
						</a>
						<div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
							<a class="dropdown-item nav-link" href="" style="color: rgb(0, 0, 0)"> My Profile </a>
							<a class="dropdown-item nav-link" href="{% url 'centralapp:logout' %}" style="color: rgb(0, 0, 0)"> Logout </a>
						</div>
					</li>
					{% else %}
					<li class="nav-item dropdown">
						<a class="nav-link mx-2" style="background:#3a8684;color:white;border-radius: 8px;" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" >
							Sign Up
						</a>
						<div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
							<a class="dropdown-item" href="{% url 'patient:patientRegister' %}">Patient</a>
							<a class="dropdown-item" href="{% url 'doctor:doctorRegister' %}">Doctors</a>
						</div>
					</li>
					<li class="nav-item">
						<a class="nav-link mx-2" style="background:#3a8684;color:white;border-radius: 8px;" href="{% url 'centralapp:login' %}">Login</a>
					</li>
					{% endif %}
					{% endif %}
					{%endwith%}
				</li>
			</ul>
		</div>


	</nav>
	
	<!-- <button id="scrollDown" onclick="topFunction()"><i class="fas fa-chevron-down"></i></button> -->
	<a href="#startOfPage" data-toggle="tooltip" data-placement="left" title="Scroll Up" id="scrollUp"><span><i
				class="fas fa-chevron-up"></i></span></a>
	<a href="#endOfPage" data-toggle="tooltip" data-placement="left" title="Scroll Down" id="scrollDown"><span><i
				class="fas fa-chevron-down"></i></span></a>

  {% block body %}

  {% endblock %}
	{% with 'create_patientprofile patientvitals_input patientRegister login' as list%}
	
		{% if request.resolver_match.url_name not in list.split %}
			<div class="col-sm-3 sidebar">
				<ul class="list-group ">
					<li class="list-group-item  heads">For You And Your Family</li>
					<ul class="list-group">
						<a class='list-group-item list-group-item-action {% if request.resolver_match.url_name == "Inside_health_records" %}active{% endif %} ' href="{% url 'centralapp:Inside_health_records' %}">What's in my health record </a>
						<a class='list-group-item list-group-item-action {% if request.resolver_match.url_name == "patients_how_to_use" %}active{% endif %} ' href="{% url 'centralapp:patients_how_to_use' %}">How to use my health record </a>
					</ul>
					<li class="list-group-item  heads">For HealthCare Professionals</li>
					<ul class="list-group">
						<a class='list-group-item list-group-item-action {% if request.resolver_match.url_name == "doc_how_to_use" %}active{% endif %} ' href="{% url 'centralapp:doc_how_to_use' %}">Maintaining health records </a>
					</ul>
					<li class="list-group-item  heads">Know more about diseases</li>
					<ul class="list-group">
						<a class='list-group-item list-group-item-action {% if request.resolver_match.url_name == "Aids" %}active{% endif %} ' href="{% url 'centralapp:Aids' %}">AIDS</a>
						<a class='list-group-item list-group-item-action {% if request.resolver_match.url_name == "Cancer" %}active{% endif %} ' href="{% url 'centralapp:Cancer' %}">Cancer</a>
						<a class='list-group-item list-group-item-action {% if request.resolver_match.url_name == "Heart_disorder" %}active{% endif %} ' href="{% url 'centralapp:Heart_disorder' %}">Heart Disorders</a>
						<a class='list-group-item list-group-item-action {% if request.resolver_match.url_name == "Hypertension" %}active{% endif %} ' href="{% url 'centralapp:Hypertension' %}">Hypertension</a>
						<a class='list-group-item list-group-item-action {% if request.resolver_match.url_name == "Diabetes" %}active{% endif %} ' href="{% url 'centralapp:Diabetes' %}">Diabetes</a>
					</ul>
					<!-- <a class='list-group-item list-group-item-action heads {% if request.resolver_match.url_name == "About_us" %}active{% endif %} ' href="{% url 'centralapp:About_us' %}">About Us</a> -->
					<a class='list-group-item list-group-item-action heads {% if request.resolver_match.url_name == "FAQS" %}active{% endif %} ' href="{% url 'centralapp:FAQS' %}">FAQs</a>
					<!-- <a class='list-group-item list-group-item-action heads {% if request.resolver_match.url_name == "Covid_19" %}active{% endif %} ' href="{% url 'centralapp:Covid_19' %}">Covid-19 Checkpoints</a> -->

				</ul>
			</div>
		</div>
	</div>
	{% endif%}
	{%endwith%}

	<!-- Footer -->
	<div id="endOfPage" >

	</div>
	<footer class="page-footer footer font-small mdb-color" style="background:linear-gradient(90deg, #24a19c,#cedebd);">

		<!-- Footer Links -->


			<!-- Footer links -->
			<div class="row text-center ml-5 text-md-left mt-3">

				<!-- Grid column -->
				<hr class="w-100 clearfix d-md-none">
				<div class="col-md-3 col-lg-3 col-xl-3 mx-auto mt-3 footer-style">
					<h6 class="text-uppercase mb-2 " >Know-hows</h6>
					<p>
						<a href="{% url 'centralapp:Inside_health_records' %}" class="useful_links">What's in my health record</a><br>
						<a href="{% url 'centralapp:patients_how_to_use' %}" class="useful_links">How to use my health record</a><br>
						<a href="{% url 'centralapp:doc_how_to_use' %}" class="useful_links">How to use the health record (for doctors)</a><br>
						<a href="{% url 'centralapp:FAQS' %}" class="useful_links">FAQs</a><br>
					</p>
				</div>
				<!-- Grid column -->
				<div class="col-md-3 col-lg-3 col-xl-3 mx-auto mt-3 footer-style">
					<h6 class="text-uppercase mb-2 font-weight-bold" > Other useful links</h6>
					<div class="no-bullet-list two-column-list">
						<!-- <a href="{% url 'centralapp:Covid_19' %}" class="useful_links">Covid-19 checkpoints</a> -->
<br>

						<h6 class="mt-2 font-weight-bold">Learn about diseases</h6>

						<ul>
						<li><a href="{% url 'centralapp:Cancer' %}" class="useful_links">Cancer</a><br></li>
						<li><a href="{% url 'centralapp:Aids' %}" class="useful_links">AIDS</a><br></li>
						<li><a href="{% url 'centralapp:Diabetes' %}" class="useful_links">Diabetes</a><br></li>
						<li><a href="{% url 'centralapp:Heart_disorder' %}" class="useful_links">Heart Disorders</a><br></li>
						<li><a href="{% url 'centralapp:Hypertension' %}" class="useful_links">Hypertension</a><br></li>

						</ul>
						</div>

				</div>
				<!-- Grid column -->

				<hr class="w-100 clearfix d-md-none">

				<!-- Grid column -->

				<div class="col-md-2 col-lg-2 col-xl-2 mx-auto mt-3 no-bullet-list footer-style">
					<h6 class="text-uppercase mb-2 font-weight-bold">Our Team</h6>
					<ul>
						<li>Vinita Patil<br></li>

				</div>
				<!-- Grid column -->
				<hr class="w-100 clearfix d-md-none ">

				<!-- Grid column -->
				<div class="col-md-3 col-lg-3 col-xl-3 mr-5 mt-3 footer-style">
					<h6 class="text-uppercase mb-2 font-weight-bold ">Contact</h6>
                    <p>
                        <i class="fa fa-home mr-3"></i>Jalgaon
                    </p>
                    <p>
                        <i class="fa fa-envelope mr-3 "></i> vinita.patil@gmail.com
                    </p>
                    <p>
                        <i class="fa fa-phone mr-3"></i> +91 0000000000
                    </p>

				</div>
				<!-- Grid column -->

			</div>
			<!-- Footer links -->

			<hr>

			<!-- Grid row -->
			<div class="row d-flex align-items-center footer-style">
				<!-- Grid column -->
				<div class="col-md-11 col-lg-11">
					<!--Copyright-->
					<p class="text-center">© 2024 Copyright:
						<strong> PHD Project</strong>
					</p>
				</div>
			</div>
			<!-- Grid row -->


		<!-- Footer Links -->
	</footer>

</body>
</html>

centralapp/templates/centralapp/faqs.html
{% extends 'centralapp/base.html' %}
{% block body %}
{% load static %}
<div class="container-fluid">
    <div class="typewriter-2">FAQS..</div>
    <div class="row my-4">
        <div class="col-sm-4 p-2 ml-auto">
            <h2 style="text-align: center; font-family: 'Grandstander';font-size: 2.5em;">For Patients</h2>

            <button class="accordion">Who can access my health record?</button>
            <div class="panel">
                <div class="panel-content">
                    <p>Only <strong>verified healthcare professionals</strong> registered at PHD Project can access your health record.</p>
                </div>
                
            </div>

            <button class="accordion">Can I not change any data in my health record?</button>
            <div class="panel">
                <div class="panel-content">
                    <p><strong>No.</strong> At PHD Project, we give the privilege to edit the information on your health
                        record only to registered medical professionals whom you choose.
                    </p>
                </div>
                
            </div>

            <button class="accordion">How do I give access to a doctor?</button>
            <div class="panel">
                <div class="panel-content">
                    <p>Login to PHD Project and navigate to the "My Doctors" section on your dashboard.
                        You will find an access code on top of the section that opens. This access code is
                        <strong>unique</strong>
                        to you
                        and is <strong>highly confidential</strong>. This code <strong>shall not be shared</strong>
                        with any individual save the doctor whom you wish to grant access.
                    </p>
                </div>
                
            </div>
            <button class="accordion">What if I take certain medications
                without<br> medical supervision? How do I add it to my health record?</button>
            <div class="panel">
                <div class="panel-content">
                    <p>There is a separate section of your health record which you can edit.
                        This includes information about any <strong>medication/supplements</strong> that you are taking without medical
                        supervision. You can add the medicines as well as any <strong>notes about general well-being</strong>
                        that you wish to be displayed to the doctor managing your health records.
                    </p>
                </div>
                
            </div>
        </div>

        <div class="col-sm-4 p-2 ml-auto ">
            <h2 style="text-align: center; font-family: 'Grandstander';font-size: 2.5em;">For Doctors</h2>

            <button class="accordion">What all information is needed to create<br> an account
                at PHD Project?
            </button>
            <div class="panel">
                <div class="panel-content">
                    <p>We would like to have the following details:
                    <ul>
                        <li>Your registration number (issued by the Govt. of India)</li><br>
                        <strong>The following details are optional:</strong><br>
                        <li>Educational qualifications</li>
                        <li>Work experience and/or specialisations</li>
                    </ul>
                    </p>
                </div>
                
            </div>

            <button class="accordion">How do I access a patient's record?</button>
            <div class="panel">
                <div class="panel-content">
                    <p>Login to PHD Project and navigate to the <strong>"My Patients"</strong> section in the dashboard.
                        Click on <strong>"Add a patient"</strong> option. You will be prompted to enter an access code.
                        This code is unique to every patient. Your patient will provide this code to you
                        after which you shall be able to edit his/her health record. </p>
                </div>
                
            </div>

            <button class="accordion">Is some minimum experience required to be able to
                register at PHD Project?</button>
            <div class="panel">
                <div class="panel-content">
                    <p>No. The only compulsory requirement is the presence of a registration number issued by the
                        <strong>Medical Council of India (MCI).</strong> </p>
                </div>
                
            </div>
            <button class="accordion">Do I need the access code everytime I access my patient's
                record?</button>
            <div class="panel">
                <div class="panel-content">
                    <p><strong>No.</strong> Once you add a patient to your patients list, you will be able to access his/her record
                        until the former changes the access code. </p>
                </div>
                
            </div>
            <button class="accordion">I will need Lab test reports as well for proper diagnosis. Is
                there
                some provision for this as well?</button>
            <div class="panel">
                <div class="panel-content">
                    <p><strong>Yes.</strong> There is a separate section of the health record that includes the test reports of
                        all the tests the patient has undergone.
                    </p>
                </div>
                
            </div>
            <script>
                var acc = document.getElementsByClassName("accordion");
                var i;
                for (i = 0; i < acc.length; i++) {
                    acc[i].addEventListener("click",function(){
                    this.classList.toggle("active-2");
                    var panel = this.nextElementSibling;
                    if (panel.style.maxHeight) {
                        panel.style.maxHeight = null;
                    } else {
                        panel.style.maxHeight = panel.scrollHeight + "px";
                    }
                    
                    });
                }
            </script>

        </div>

{% endblock %}

centralapp/templates/centralapp/temp.html
{{isuser}}
{{usertype}}