MedicDiary/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as authentication_views


urlpatterns = [

    path('admin/', admin.site.urls),
    path('', include('centralapp.urls')),
    path('', include('doctor.urls')),
    path('', include('patient.urls')),
    path('login/',authentication_views.LoginView.as_view(template_name='MedicDiary/login.html'),name='login'),
]

from django.conf import settings
from django.conf.urls.static import static

urlpatterns += [
    # ... the rest of your URLconf goes here ...
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

centralapp/urls.py
from . import views
from django.urls import path
from django.contrib.auth import views as authentication_views

app_name = 'centralapp'
urlpatterns = [

    path('',views.mainpage,name='mainpage'),
    path('About_us/',views.About_us,name ='About_us'),
    path('Aids/',views.Aids,name ='Aids'),
    path('Cancer/',views.Cancer,name ='Cancer'),
    path('Covid-19/',views.Covid_19,name ='Covid_19'),
    path('Diabetes/',views.Diabetes,name ='Diabetes'),
    path('FAQS/',views.FAQS,name ='FAQS'),
    path('Heart_disorder/',views.Heart_disorder,name ='Heart_disorder'),
    path('medical_practitioners/How_to_use',views.doc_how_to_use,name ='doc_how_to_use'),
    path('friends-and-family/How_to_use',views.patients_how_to_use,name ='patients_how_to_use'),
    path('Hypertension/',views.Hypertension,name ='Hypertension'),
    path('Inside_health_records/',views.Inside_health_records,name ='Inside_health_records'),
    path('login/',views.login,name='login'),
    path('logout/',views.logout_user,name='logout'),
    # path('logout/', authentication_views.LogoutView.as_view(template_name='centralapp/logout.html'), name='logout'),
     path('searchBar/',views.searchBar,name='searchBar'),
]

doctor/urls.py
from . import views
from django.urls import path
from django.contrib.auth import views as authentication_views

app_name = 'doctor'
urlpatterns = [
    path('doctorProfile/', views.doctorProfile, name='doctorProfile'),
    path('createDoctorProfile/',views.create_doctorprofile,name ='create_doctorprofile'),
    path('doctorRegister/',views.doctorRegister,name = 'doctorRegister'),
    path('PatientList/',views.PatientList,name = 'PatientList'),
    path('pat_profile/<int:p>', views.pat_profile,name = 'pat_profile'),
    path('newReport/<int:p>',views.newReport,name="newReport"),
    path('addReport/',views.addReport,name="addReport"),
    path('addPatient/',views.addPatient,name="addPatient"),
    path('editdocprofile/',views.editdoctorprofile,name="editdoctorprofile"),

    # path('logout/', authentication_views.LogoutView.as_view(template_name='centralapp/logout.html'), name='logout'),
    # path('mypatients',views.mypatients,name = "mypatients"),
    # path('editDoctor/',views.editDoctor,name = 'editDoctor'),
]















# =============================================================================================
# =============================================================================================


    #   path('registerpage/',views.registerpage,name ='registerpage'),
    #    path('signup/',views.signup, name ='signup'),
    #      path('logind/',views.loginn, name ='logind'),
    #       path('myPatients/', views.myPatients, name='myPatients'),
    #   #     path('doctorProfile/', views.doctorProfile, name='doctorProfile'),
    #       path('addpatient/', views.addpatient, name='addpatient'),
    #       path('doctorRecords/<str:p_username>', views.doctorRecords, name='doctorRecords'),
    #        path('addRecord/', views.addRecord, name='addRecord'),
    #         path('newReport/', views.newReport, name='newReport'),
    #
    #
    # path('doctorprofile/', views.doctor_profile, name='doctor_profile'),
    #
    #
    #
    # # path('doclogin/',views.doclogin,name ='doclogin'),
    # # path('docregister/',views.docregister,name ='docregister')

patient/urls.py
from . import views
from django.urls import path
from django.contrib.auth import views as authentication_views

app_name = 'patient'
urlpatterns = [
    path('Medications/', views.medications, name='medications'),
    path('LabReports/', views.labreports, name='labreports'),
    path('patientProfile/', views.patientProfile, name='patientProfile'),
    path('patientRecords/', views.patientRecords, name='patientRecords'),
    path('createPatientProfile/',views.create_patientprofile,name ='create_patientprofile'),
    path('patientvitals/',views.patientvitals_input,name ='patientvitals_input'),
    path('patientRegister/',views.patientRegister,name = 'patientRegister'),
    path('editPatient/',views.editPatient,name = 'editPatient'),
    path('editPatientVitals/',views.editPatientVitals,name = 'editPatientVitals'),
    path('addLabReports/',views.addLabReports,name = 'addLabReports'),
    path('logout/', authentication_views.LogoutView.as_view(template_name='centralapp/logout.html'), name='logout'),   
    # path('patLogin/', auth_views.login, {'template_name': 'patient/login.html'}, name = 'login'),
    # path('login/',authentication_views.LoginView.as_view(template_name='patient/patlogin.html'),name='patLogin'),
    # path('patLogout/',authentication_views.LogoutView.as_view(template_name='patient/patlogout.html'),name='patLogout'),
]














# ======================================================================================
# ======================================================================================


    # path('personalNotes/', views.personalNotes, name='personalNotes'),
    #
    #
    # # path('login/',views.login,name ='login'),
    # path('registerpage/',views.registerpage,name ='registerpage'),
    # # path('profile/',views.profile,name ='profile'),
    # # path('patientregister/',views.patientregister,name = 'patientregister'),
    # # path('makeprofilepage/',views.makeprofilepage,name = 'makeprofilepage'),
    # path('signup/',views.signup, name ='signup'),
    # path('loginp/',views.loginn, name ='loginp'),
    # path('logout/',views.logout, name ='logout'),
    #  path('addnotes/',views.addnotes, name ='addnotes'),

patient/views.py
from django.shortcuts import render,redirect, get_object_or_404
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate,login,logout
from django.contrib import messages
from .forms import PatientRegisterForm,PatientProfileForm,PatientVitalsForm
from django.contrib.auth.decorators import login_required
from .models import PatientProfile,PatientVitals,Records,LabReports
from django.contrib.auth import logout
import pytesseract
from PIL import Image
#
# def auth(str):
#     return(hash(str))

# def create_profile(request):
#     form = ProfileForm(request.POST or None)  #class created in forms.py
#     if form.is_valid():
#         form.save()
#         return redirect('centralapp:mainpage')
#     return render(request,'centralapp/profile-create.html',{'form':form})
#
def patientRegister(request):
    if request.method =='POST':
        form = PatientRegisterForm(request.POST)
        if form.is_valid():
            # form.save()
            # username = form.cleaned_data.get('username')
            # email = form.cleaned_data.get('email')
            # return redirect('login')
            user = form.save(commit=False)
            user.usertype= 1
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            # email = form.cleaned_data['email']
            # user.AccessCode = hash(email)
            user.set_password(password)
            user.save()
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('patient:create_patientprofile')
    else:
        form = PatientRegisterForm()
    return render(request,'patient/patientregister.html',{'form':form})

# @login_required
# def patient_create(request):
#     form = PatientForm()
#     if request.method == 'POST':
#         form = PatientForm(request.POST, request.FILES)
#         if form.is_valid():
#             patient = form.save(commit=False)
#             patient.user = request.user
#             patient.save()
#             return redirect('patient-detail')
#     context = {'form':form}
#     template = 'userinfo/patients/patient-create.html'
#     return render(request, template, context)

@login_required
def create_patientprofile(request):
    if request.method =='POST':
        form = PatientProfileForm(request.POST)
        if form.is_valid():

            patient = form.save(commit=False)
            # name = form.cleaned_data['name']
            # patient.AccessCode = hash(name)
            patient.patient = request.user
            patient.save()
            # form.patient = request.user
            # form.save()
            patient=PatientProfile.objects.filter(patient=request.user)[0]
            print(patient.address)
            print(hash(patient.address))
            patient.access_code=hash( str(patient.id) +patient.address)
            patient.userid=request.user.id ##changed
            patient.save()
            
            return redirect('patient:patientvitals_input')
    else:
        form = PatientProfileForm()
    return render(request,'patient/patient-profile-create.html',{'form':form})

@login_required
def patientvitals_input(request):
    if request.method =='POST':
        form = PatientVitalsForm(request.POST)
        if form.is_valid():
            patientv = form.save(commit=False)
            patientv.patientv = request.user
            patientv.save()
            # form.save()
            return redirect('patient:patientProfile')
    else:
        form = PatientVitalsForm()
    return render(request,'patient/patientvital_info.html',{'form':form})

 
@login_required
def patientProfile(request):
    profile = PatientProfile.objects.get(patient=request.user)
    return render(request, 'patient/patient_profile.html',{'profile':profile})

@login_required
def patientRecords(request):
    vitals = PatientVitals.objects.get(patientv=request.user)
    patient=PatientProfile.objects.filter(patient=request.user)[0]
    all_reports=list(Records.objects.filter(patient_id=patient.id).order_by('id').reverse())
    count=0
    rec=[]
    for r in all_reports:
        if count ==1:
            break
        rec.append(r)
        count=count+1


        for report in rec:
            des=report.medication
            med=des.split(":")
            m_list=[]
            for m in med:
	            dosage=m.split("/")
	            m_list.append(dosage)

            report.medication=m_list

    all_lab=LabReports.objects.filter(patientl=request.user).order_by('id').reverse()
    count=0
    current=[]
    for lab in all_lab:
        if count==1:
            break
        current.append(lab)
        count=count+1


    return render(request, 'patient/patient_records.html',{'vitals':vitals,'Reports':rec,"lab_rec":current})

@login_required 
def labreports(request):
    all_lab=LabReports.objects.filter(patientl=request.user)
    print(request.user.id)

    return render(request, 'patient/labreports.html',{"reports":all_lab})


@login_required
def addLabReports(request):
    if request.method == "POST":
        new_report = LabReports()
        new_report.patientl = request.user
        new_report.report_name = request.POST['report_name']
        new_report.report_date = request.POST['report_date']
        new_report.labreportfile = request.FILES['file']
        new_report.save()

        # Extract text from the uploaded report
        extracted_text = extract_text_from_image(new_report.labreportfile)
        print("Extracted Text:")
        print(extracted_text)

        return redirect('patient:labreports')
    else:
        return redirect('patient:labreports')

def extract_text_from_image(image):
    pytesseract.pytesseract.tesseract_cmd = r'C:\Program Files\Tesseract-OCR\tesseract.exe'
    extracted_text = pytesseract.image_to_string(Image.open(image))
    # Replace '.' and ',' with newline character '\n'
    extracted_text = extracted_text.replace('.', '\n').replace(',', '\n')
    return extracted_text




@login_required
def medications(request):
    patient=PatientProfile.objects.filter(patient=request.user)[0]
    all_reports=Records.objects.filter(patient_id=patient.id).order_by('id').reverse()
    
    print(len(all_reports.reverse()))
    for report in all_reports:
        des=report.medication
        med=des.split(":")
        m_list=[]
        for m in med:
	        dosage=m.split("/")
	        m_list.append(dosage)

        report.medication=m_list
        

    return render(request, 'patient/medications.html',{'Reports':all_reports})

@login_required
def editPatient(request):
    patient = get_object_or_404(PatientProfile, patient=request.user)
    # patient = PatientProfile.objects.get(patient=request.user)
    # if request.method == 'POST':
    form = PatientProfileForm(request.POST, request.FILES, instance=patient)
    # if request.method == 'POST':

    if form.is_valid():
        patient = form.save(commit=False)
        patient.patient = request.user
        patient.save()
        return redirect('patient:patientProfile')
    # else:
    #     form = PatientProfileForm()
    return render(request,'patient/patient-profile-edit.html',{'form':form})

@login_required
def editPatientVitals(request):
    patientv = get_object_or_404(PatientVitals, patientv=request.user)
    # if request.method == 'POST':
    form = PatientVitalsForm(request.POST, request.FILES, instance=patientv)
    if form.is_valid():
        patientv = form.save(commit=False)
        patientv.patientv = request.user
        patientv.save()
        return redirect('patient:patientRecords')
    # else:
        # form = PatientVitalsForm()
    return render(request,'patient/patient-vitals-edit.html',{'form':form})



#
# def logout_view(request):
#     logout(request)
#     return render(r'^logout/$', 'django.contrib.auth.views.logout',
#                           {'next_page': '/successfully_logged_out/'})
#





# ===============================================================
# =================================================================
# ============================================================================

# from django.shortcuts import render,redirect
# from django.http import HttpResponse
# from django.contrib.auth.models import User
# from django.contrib.auth import authenticate,login,logout
# from django.contrib import messages
# from django.middleware.csrf import get_token
# # from .forms import RegisterForm, ProfileForm
# # from .models import Profile
# from django.contrib.auth.decorators import login_required
#
#
# from .models import patient_details,notes
# import random
# import string
#
# def get_random_string(length):
#     # Random string with the combination of lower and upper case
#     letters = string.ascii_letters
#     result_str = ''.join(random.choice(letters) for i in range(length))
#     print("Random string is:", result_str)
#
#
# def patientProfile(request):
#     return render(request, 'patient/patient_profile.html')
# def patientRecords(request):
#     return render(request, 'patient/patient_records.html')
#
# def labreports(request):
#     return render(request, 'patient/labreports.html')
# def medications(request):
#     return render(request, 'patient/medications.html')
#
# def registerpage(request):
#     return render(request,'patient/register.html')
#
# def signup(request):
#     if request.method=="POST":
#         fname=request.POST['fname']
#         lname=request.POST['lname']
#
#         username=request.POST['username']
#         password=request.POST['password']
#         email=request.POST['email']
#
#
#         if len(username)>15:
#             messages.error(request,'length of username should be less than15')
#             return redirect('patient:registerpage')
#
#         myuser=User.objects.create_user(username,email,password)
#         myuser.first_name=fname

patient/templates/patient/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>

	<!-- Required meta tags -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<!-- Bootstrap CSS -->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
	<link rel="stylesheet"
	href="https://fonts.googleapis.com/css?family=Pacifico" />
	<link rel="stylesheet"
	href="https://fonts.googleapis.com/css?family=Cinzel" />
	<link rel="stylesheet"
	href="https://fonts.googleapis.com/css?family=Oswald"/>
	<link rel="stylesheet"
	href="https://fonts.googleapis.com/css?family=Grandstander"/>
	<link rel="stylesheet"
	href="https://fonts.googleapis.com/css?family=Ubuntu"/>
	<link rel="stylesheet"
	href="https://fonts.googleapis.com/css2?family=Itim" >

	<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
	<script src="https://kit.fontawesome.com/032a738741.js" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="{% static 'patient/css_files/style.css' %}">
	<link rel="icon" type="image/png" href="{% static 'patient/Images/icon.png' %}"/>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"/>
	<link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
	<script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
	<script src="{% static 'patient/js/app.js' %}"></script>
    <!--<script src="https://kit.fontawesome.com/b99e675b6e.js"></script>-->
	<title>PHD Project</title>
</head>
<body style="background: #f7f7ee">
	<script>
	   AOS.init();
	   document.getElementById("defaultOpen").click();
    </script>
	<nav class="navbar navbar-expand-lg navbar-light nav-bg" id="navstyle" >
		<a class="navbar-brand" href="{% url 'centralapp:mainpage' %}" style="font-family: Cinzel; font-size: 40px !important; color: white;" >
			<img src="{% static 'patient/Images/icon.png' %}" width="50" height="50" class="d-inline-block align-top" alt="" loading="lazy">
			PHD Project
		</a>

		<div class="collapse navbar-collapse" id="navbarSupportedContent" style="font-size:20px; ">
			<ul class="navbar-nav ml-auto">

				<!-- <li class="nav-item active">
					<a class="nav-link" href="#" style="color: rgb(0, 0, 0)"> Sign In </a>
				</li> -->
				{% if user.is_authenticated %}
				<li class="nav-item dropdown">
					
						<a class="nav-link" style="background:#3a8684;color:white;border-radius: 8px;" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true"
							aria-expanded="false">
							Hey {{request.user.username|title }}</a>
							<div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
								<a class="dropdown-item nav-link " href="{% url 'patient:patientProfile' %}" style="color: rgb(0, 0, 0)"> My
									Profile </a>
								<a class="dropdown-item nav-link " href="{% url 'centralapp:logout' %}" style="color: rgb(0, 0, 0)"> Logout </a>
							</div>
						
					
					
				</li>
				{% endif %}
			</ul>
		</div>
	</nav>


	{% with 'create_patientprofile patientvitals_input patientRegister' as list%}
		{% if request.resolver_match.url_name not in list.split %}

    <div id="sidebar" >
        <div class="toggle-btn" onclick="toggleSideBar()">
            <span style='font-size:20px;'>&#9776;</span>
        </div>

        <ul>
					  <a href="{% url 'patient:patientRecords' %}"><li>Dashboard</li></a>
            <a href="{% url 'patient:medications' %}"><li>Health Records</li></a>
            <a href="{% url 'patient:labreports' %}"><li>Lab Reports</li></a>
						<a href="{% url 'patient:patientProfile' %}"><li>Profile page</li></a>
            <!-- <a href=""><li>Personal notes</li></a> -->
            <!-- <a href="{% url 'patient:patientProfile' %}"><li>Edit your profile</li></a>
            <a href="{% url 'patient:patientRecords' %}"><li>Homepage</li></a> -->
        </ul>
	</div>
	{% endif %}
	{% endwith %}

  {% block patient_base %}

  {% endblock %}


	<!-- Footer -->
	<footer class="page-footer footer font-small mdb-color" style="background:linear-gradient(90deg, #24a19c,#cedebd);">

		<!-- Footer Links -->


			<!-- Footer links -->
			<div class="row text-center ml-5 text-md-left ">

				<!-- Grid column -->
				<hr class="w-100 clearfix d-md-none">
				<div class="col-md-3 col-lg-3 col-xl-3 mx-auto mt-3 footer-style">
					<h6 class="text-uppercase mb-2 " >Know-hows</h6>
					<p>
						<a href="{% url 'centralapp:Inside_health_records' %}" class="useful_links">What's in my health record</a><br>
						<a href="{% url 'centralapp:patients_how_to_use' %}" class="useful_links">How to use my health record</a><br>
						<a href="{% url 'centralapp:doc_how_to_use' %}" class="useful_links">How to use the health record (for doctors)</a><br>
						<a href="{% url 'centralapp:FAQS' %}" class="useful_links">FAQs</a><br>
					</p>
				</div>
				<!-- Grid column -->
				<div class="col-md-3 col-lg-3 col-xl-3 mx-auto mt-3 footer-style">
					<h6 class="text-uppercase mb-2 font-weight-bold" > Other useful links</h6>
					<div class="no-bullet-list two-column-list">
						<!-- <a href="{% url 'centralapp:Covid_19' %}" class="useful_links">Covid-19 checkpoints</a> -->
<br>
						<h6 class="mt-2 font-weight-bold">Learn about diseases</h6>

						<ul>
						<li><a href="{% url 'centralapp:Cancer' %}" class="useful_links">Cancer</a><br></li>
						<li><a href="{% url 'centralapp:Aids' %}" class="useful_links">AIDS</a><br></li>
						<li><a href="{% url 'centralapp:Diabetes' %}" class="useful_links">Diabetes</a><br></li>
						<li><a href="{% url 'centralapp:Heart_disorder' %}" class="useful_links">Heart Disorders</a><br></li>
						<li><a href="{% url 'centralapp:Hypertension' %}" class="useful_links">Hypertension</a><br></li>

						</ul>
						</div>
				</div>
				<!-- Grid column -->

				<hr class="w-100 clearfix d-md-none">

				<!-- Grid column -->

				<div class="col-md-2 col-lg-2 col-xl-2 mx-auto mt-3 no-bullet-list footer-style">
					<h6 class="text-uppercase mb-2 font-weight-bold">Our Team</h6>
					<ul>
						<li>Vinita Patil<br></li>

						</ul>
						<a href="{% url 'centralapp:About_us' %}" class="useful_links" style="font-weight:bold">More about us</a>

				</div>
				<!-- Grid column -->
				<hr class="w-100 clearfix d-md-none ">

				<!-- Grid column -->
				<div class="col-md-3 col-lg-3 col-xl-3 mt-3 footer-style">
					<h6 class="text-uppercase mb-2 font-weight-bold ">Contact</h6>
                    <p>
						<i class="fa fa-home mr-3"></i>Jalgaon
					</p>
					<p>
						<i class="fa fa-envelope mr-3 "></i> vinita.patil
					</p>
					<p>
						<i class="fa fa-phone mr-3"></i> +91 0000000000
					</p>

				</div>
				<!-- Grid column -->

			</div>
			<!-- Footer links -->

			<hr>

			<!-- Grid row -->
			<div class="row d-flex align-items-center footer-style">
				<!-- Grid column -->
				<div class="col-md-11 col-lg-11">
					<!--Copyright-->
					<p class="text-center">© 2024 Copyright:
						<strong> PHD Project</strong>
					</p>
				</div>
			</div>
			<!-- Grid row -->


		<!-- Footer Links -->
	</footer>

</body>
</html>

patient/templates/patient/patient_records.html
{% extends 'patient/base.html' %}

{% block patient_base %}
{% load static %}

<div class="container" id="main-content" style="margin-left: 160px;">
    <div class="row dashboard-content">
        <div class="col">
        <h2 style="display: block;">Current Medication </h2>
        {% for report in Reports%}

        <div class="prescription" style="background: #fff7c8 ;padding: 1em;">
            <p style="font-size: x-large;"><span><b>Doctor: </b> {{report.doctor_name}}</span>
            <span style="float: right;"><b>Date: </b>{{report.date}}</span></p>

            <p><b>Symptoms: </b>{{report.Symptoms}}</p>
            <p><b>Diagnosis: </b>{{report.diagnosis}}</p>
            <table class="table table-bordered table-sm">
                <thead class="thead-dark">
                <tr>
                    <th>Medicine</th>
                    <th>Dosage</th>
                    <th>For</th>
                </tr>
                </thead>
                <tbody>
                {%for med in report.medication%}
                <tr>
                    {%for each in med%}
                    <td>{{each}}</td>
                    {%endfor%}
                </tr>
                {%endfor%}

                </tbody>
            </table>
            <p><strong>Additional Precautions:</strong> {{report.additional_precautions}}</p>
        </div>
        <hr>
        {% empty %}
        <div  style="margin-top:7%;">
            <p style="font-size: 20px;">
                <b>
                    NO MEDICAL HISTORY !!
                </b>
            </p>
        </div>
        {%endfor%}

        <div class="container">
            <button class="edit-option-buttons" style="font-size: 18px;">
                <a href="{% url 'patient:medications' %}">View all prescriptions</a>
            </button>
        </div>
    </div>
    </div>
    <div class="row dashboard-content">
        <h2>Recent Lab reports </h2>
        <div class="container" id="main-content">
        <div class="row my-4">
            <div class="col">


                    <table class="table table-striped">
                        <thead class="thead-dark">
                            <tr>
                                <th>Report Name</th>
                                <th>Report Date</th>
                                <th>Preview</th>
                                <th>Download</th>
                            </tr>
                        </thead>
                        <tbody>
                            {%for report in lab_rec %}
                                <tr>
                                    <td>{{report.report_name}}</td>
                                    <td>{{report.report_date}}</td>
                                    <td><a class="prev-download-btn" href="{{report.labreportfile.url}}" target="_blank" >Preview</a></td>
                                    <td><a class="prev-download-btn" href="{{report.labreportfile.url}}" download>Download</a></td>


                                </tr>
                            {%endfor%}
                        </tbody>
                    </table>

            </div>
        </div>
        </div>
        <div class="container">
            <button class="edit-option-buttons" style="font-size: 18px;">
                <a href="{% url 'patient:labreports' %}">View reports</a>
            </button>
        </div>
    </div>
    <div class="row dashboard-content">
       <div><h2>General Vitals </h2></div>
       <div class="container" style="width: 100%;">
        <div class="row my-5" style="font-size: 20px;">
            <div class="col-5 text-center" >
                <div class="row my-3">
                    <div class="col-lg-6 profile-content">
                        <b>HEIGHT : </b>
                    </div>
                    <div class="col-lg-6 profile-content">
                        {{vitals.Height_in_Centimeters}} Centimeters
                    </div>
                </div>
                <div class="row my-3">
                    <div class="col-lg-6 profile-content">
                        <b>WEIGHT :</b>
                    </div>
                    <div class="col-lg-6 profile-content">
                        {{vitals.Weight_in_kilograms}} Kgs
                    </div>
                </div>
                <div class="row my-3">
                    <div class="col-lg-6 profile-content">
                        <b>SMOKER OR NOT :</b>
                    </div>
                    <div class="col-lg-6 profile-content">
                        {{vitals.Smoker_or_not}}
                    </div>
                </div>
            </div>
            <div class="col-7 text-center">
                <div class="row my-3">
                    <div class="col-lg-6 profile-content">
                        <b>ALLERGIES :</b>
                    </div>
                    <div class="col-lg-6 profile-content">
                        {{vitals.Allergies}}
                    </div>
                </div>
                <div class="row my-3">
                    <div class="col-lg-6 profile-content">
                        <b>CHRONIC CONDITIONS : </b>
                    </div>
                    <div class="col-lg-6 profile-content">
                        {{vitals.Chronic_conditions}}
                    </div>
                </div>
            </div>
        </div>
       </div>

<!-- height :      {{vitals.Height_in_Centimeters}}<br>
        <table class="table table-striped">
            <thead class="thead-dark">
                <tr>
                    <th>Report Name</th>
                    <th>Report Date</th>
                    <th>Download</th>
                    <th>Preview</th>

                </tr>
            </thead>
            <tbody>
                {%for report in lab_rec%}
                <tr>
                    <td>{{report.report_name}}</td>
                    <td>{{report.report_date}}</td>

                    <td><a class="prev-download-btn" href="{{report.labreportfile.url}}" download>Download</a></td>
                    <td><a class="prev-download-btn" href="{{report.labreportfile.url}}" >Preview</a></td>

                </tr>
                {%endfor%}
            </tbody>
        </table>

    </div>
    <div class="row dashboard-content">
        <h2>General Vitals </h2>
        <p><br><br>
height :      {{vitals.Height_in_Centimeters}}<br>
Weight :      {{vitals.Weight_in_kilograms}}<br>
Allergies :      {{vitals.Allergies}}<br>
smoker or not :      {{vitals.Smoker_or_not}}<br>
Chronic_conditions :      {{vitals.Chronic_conditions}}<br> -->

<div class="container">
    <button class="edit-option-buttons" style="font-size: 18px; left: 50%;">
        <a href="{% url 'patient:editPatientVitals' %}">Edit info</a>
    </button>
</div>
</div>
</div>

{% endblock %}